services:
  dinogram:
    build: .
    container_name: dinogram
    env_file: .env
    depends_on: [telegram-bot-api]
    volumes:
      - dinogram-data:/app/data/
    environment:
      BOT_API_ROOT: http://telegram-bot-api:8081

  telegram-bot-api:
    image: aiogram/telegram-bot-api:7.10
    container_name: telegram-bot-api
    env_file: .env

volumes:
  dinogram-data:
