name: dinogram

services:
  bot:
    build: .
    env_file: .env
    depends_on: [telegram-bot-api]
    volumes:
      - bot-data:/app/data/
    environment:
      BOT_API_ROOT: http://telegram-bot-api:8081

  telegram-bot-api:
    image: aiogram/telegram-bot-api:9.0
    env_file: .env

volumes:
  bot-data:
