services:
  dinogram:
    image: ghcr.io/arslan-charyyev/dinogram:latest
    container_name: dinogram
    restart: unless-stopped
    depends_on: [ telegram-bot-api ]
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_API_ROOT: http://telegram-bot-api:8081

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api
    restart: unless-stopped
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID} 
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
