name: dinogram

services:
  bot:
    build: .
    env_file: .env
    depends_on: [telegram-bot-api]
    ports:
      # TODO: Delete this after piping RFB socket to internal socket
      - "5900-6000:5900-6000"
    environment:
      BOT_API_ROOT: http://telegram-bot-api:8081
      # Local .env file overwrites these vars, so we need to restore them
      DATA_DIR: /app/data/
    volumes:
      - bot-data:/app/data/
    cap_add:
      - SYS_ADMIN

  telegram-bot-api:
    image: aiogram/telegram-bot-api:9.0
    env_file: .env
    ports:
      - '8081:8081'

volumes:
  bot-data:
