name: 🦕 Deploy to a remote Docker host

on:
  workflow_dispatch: # Allow the workflow to be triggered manually from the GitHub UI
  workflow_call:
    secrets: # Allow passing secrets from the caller workflow
      DOCKER_SSH_PRIVATE_KEY:
        required: true
      DOCKER_HOST:
        required: true
      DOCKER_USER:
        required: true
      BOT_TOKEN:
        required: true
      BOT_ADMINS:
        required: true
      TELEGRAM_API_ID:
        required: true
      TELEGRAM_API_HASH:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: 📥 Check out repository code
        uses: actions/checkout@v4

      - name: 🔑 Add SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}

      - name: 🔏 Add remote host to SSH known_hosts
        run: ssh-keyscan -H ${{ secrets.DOCKER_HOST }} >> ~/.ssh/known_hosts

      - name: ⚙️ Setup Docker context
        run: |
          docker context create remote --docker "host=ssh://${{ secrets.DOCKER_USER }}@${{ secrets.DOCKER_HOST }}"
          docker context use remote

      - name: 🐳 Deploy with Docker Compose
        run: docker compose --file compose.prod.yml up -d
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_ADMINS: ${{ secrets.BOT_ADMINS }}
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
